const menu = [
  {
    id: 1,
    title: "Chicken Curry",
    category: "curry",
    price: 15.99,
    img: require("../assets/curry/chickencurry.jpg"),
    desc: `Mild Onion based curry  with stewed meat and whole spice `,
  },
  {
    id: 2,
    title: "Butter Chicken Curry",
    category: "curry",
    price: 13.99,
    img: require("../assets/curry/butterchickencurry.jpg"),
    desc: `Butter flavored tomato based curry with no bone Tandoori chicken. Most pupular curry in our restarurant

    Price
    `,
  },
  {
    id: 3,
    title: "Chicken Keema Curry",
    category: "curry",
    price: 6.99,
    img: require("../assets/curry/chickenkeemacurry.jpg"),
    desc: `Spicy curry with ground meat ( Chicken7: Mutton3) `,
  },
  {
    id: 4,
    title: "Sag Chicken Curry",
    category: "curry",
    price: 20.99,
    img: require("../assets/curry/sagChickenCurry.jpg"),
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "Plain Nan",
    category: "nan",
    price: 18.99,
    img: require("../assets/nan/garlicnan.jpeg"),
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 6,
    title: "Garlic Nan",
    category: "nan",
    price: 18.99,
    img: require("../assets/nan/garlicnan.jpeg"),
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "Keema Cheese Nan",
    category: "nan",
    price: 8.99,
    img: require("../assets/nan/keemacheesenan.jpeg"),
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "Chicken Tikka(6Pc)",
    category: "tandoori",
    price: 12.99,
    img: require("../assets/tandoori/chickentikka6pc.JPG"),
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "Tandoor Chicken(2Pc)",
    category: "tandoori",
    price: 12.99,
    img: require("../assets/tandoori/tandoorichicken2pc.JPG"),
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 10,
    title: "Chicken Chilli",
    category: "salad",
    price: 22.99,
    img: require("../assets/appetizers/chickenchiilli.jpg"),
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 11,
    title: "Momo",
    category: "salad",
    price: 22.99,
    img: require("../assets/appetizers/momo.jpg"),
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 12,
    title: "Samosa",
    category: "salad",
    price: 22.99,
    img: require("../assets/appetizers/samosa.jpg"),
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 13,
    title: "Vegetable Chowmin",
    category: "salad",
    price: 22.99,
    img: require("../assets/appetizers/vegetablechowmin.jpg"),
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
];
export default menu;
